version: '3.5'

services:
    nginx:
        image: nginx:alpine
        container_name: docker-nginx
        ports:
            - '80:80'
        volumes:
            - ./code:/code
            - ./docker/nginx/vhost:/etc/nginx/conf.d/default.conf
